/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  ASSO
 * Created: 2-set-2016
 */

CREATE TABLE cliente
(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
username VARCHAR(128),
password VARCHAR(32),
nome VARCHAR(128),
cognome VARCHAR(128),
saldo REAL
);

CREATE TABLE venditore
(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
username VARCHAR(128),
password VARCHAR(32),
nome VARCHAR(128),
cognome VARCHAR(128),
saldo REAL,
num_oggetti INTEGER
);


CREATE TABLE cofanetto
(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
genere VARCHAR(128),
titolo VARCHAR(128),
stagione VARCHAR(32),
trama VARCHAR(512),
prezzo REAL,
num_pezzi INTEGER,
url_immagine VARCHAR(128)
);


CREATE TABLE cofanetti_venditori
(
idCofanetto INTEGER,
FOREIGN KEY (idCofanetto) REFERENCES cofanetto(id) ON DELETE CASCADE,
idVenditore INTEGER,
FOREIGN KEY (idVenditore) REFERENCES venditore(id),
PRIMARY KEY (idCofanetto, idVenditore),
numero INTEGER
);

CREATE TABLE cofanetti_acquistati
(
idCofanetto INTEGER,
FOREIGN KEY (idCofanetto) REFERENCES cofanetto(id),
idCliente INTEGER,
FOREIGN KEY (idCliente) REFERENCES cliente(id),
PRIMARY KEY (idCofanetto, idCliente)
);



CREATE TABLE carrello
(
idCofanetto INTEGER,
FOREIGN KEY (idCofanetto) REFERENCES cofanetto(id),
idCliente INTEGER,
FOREIGN KEY (idCliente) REFERENCES cliente(id),
PRIMARY KEY (idCofanetto, idCliente)
);


INSERT INTO cliente(id, username, password, nome, cognome, saldo)
VALUES (default,'tizio', 'incognito', 'Bruce', 'Wayne', 550.60),
(default, 'turbowater', 'drink77', 'Homer', 'Simpson', 750.00),
(default, 'mario', 'mario50', 'Mario', 'Rossi', 83.50),
(default, 'bestcliente', 'paroladordine', 'Maria', 'Bianchi', 110.75),
(default, 'orsetto_coccoloso', '12345', 'Francesca', 'San Giorgio', 25.50);

INSERT INTO venditore(id, username, password, nome, cognome, saldo, num_oggetti)
VALUES (default, 'ullo33', 'sbrillo90', 'Giulia', 'Concas', 122.50, 3),
 (default, 'asso302', 'sassola303', 'Sara', 'Concas', 800.00, 5),
 (default, 'micione', 'sonoungatto', 'Edoardo', 'Concas', 77.55, 1),
 (default, 'gideon', 'nabbo91', 'Mattia', 'Orrù', 54.90, 2),
 (default, 'tizio22', 'prova', 'Mario', 'Bianchi', 22.50, 2);

INSERT INTO cofanetto(id, genere, titolo, stagione, trama, num_pezzi, prezzo, url_immagine)
VALUES (default, 'animazione', 'The Simpsons', 'nove', 'parodia satirica della società e dello stile di vita statunitense, impersonificati dalla famiglia Simpson, protagonista dell opera, composta da Homer, Marge e dai loro tre figli Bart, Lisa e Maggie. ', 1, 20.00, 'imm/simpson.png'),
(default, 'animazione', 'American Dad', 'uno', 'La famiglia protagonista del cartone, che vive in una cittadina della Virginia chiamata Langley Falls, è la rappresentazione dissacrante di una famiglia americana del dopo 11 settembre.', 2, 15.00, 'imm/americandad.jpg'),
(default, 'animazione', 'Futurama', 'due', 'La serie è ambientata nella New York dell anno 3000 e racconta le avventure di Philip J. Fry, fattorino di una pizzeria che il 1º gennaio dell anno 2000 finisce accidentalmente in una capsula per il sonno criogenico e si risveglia mille anni dopo, il 31 dicembre 2999, iniziando una nuova vita nel futuro.', 1, 13.50, 'imm/futurama.jpg'),
(default, 'comedy', 'Scrubs', 'serie completa', 'I protagonisti sono tre giovani medici nonchè amici che lavorano presso il Sacred Heart Hospital condividendo gioe e dolori che caratterizzano la professione medica.', 1, 80.00, 'imm/scrubs.jpg'),
(default, 'comedy', 'Modern Family', 'uno', 'racconta le vicende di una famiglia allargata che non corrisponde ai canoni tradizionali, offrendo un realistico scorcio sulla figura, in costante cambiamento, della famiglia occidentale', 1, 20.00, 'imm/modernfamily.jpg'),
(default, 'comedy', 'Friends', 'serie completa', 'La serie ruota attorno a un gruppo di sei amici a Manhattan, i maschi Ross, Chandler e Joey, e le femmine Rachel, Monica e Phoebe.', 1, 100.00, 'imm/friends.jpg'),
(default, 'crime', 'Cold Case', '1-7', 'Le vicende della serie ruotano attorno alle indagini di una fittizia divisione della polizia di Filadelfia, guidata dalla detective Lilly Rush e specializzata in casi irrisolti.', 1, 70.00, 'imm/coldcase.jpg'),
(default, 'crime', 'Breaking Bad', 'serie completa', 'progatonista della serie è il professore di liceo Walter White che dopo aver saputo di essere gravemente malato dedice di sfruttare al meglio il tempo rimanente iniziando a produrre e commerciare anfetamine nel laboratorio della scuola dove lavora, in modo da poter aiutare la sua famiglia il giorno in cui non ci sarà più', 1, 60.00, 'imm/brba.jpg'),
(default, 'crime', 'Criminal Minds', '1-9', 'Una squadra speciale dell’ FBI(l Unità di Analisi Comportamentale) supporta le polizie locali di tutto il paese in quei casi di omicidio dove probabilmente è coinvolto un serial killer.', 1, 70.00, 'imm/criminalminds.jpg'),
(default, 'fantascienza', 'Star Trek', '1', 'narra delle vicende degli umani del futuro, appartenenti a una Federazione dei pianeti uniti che riunisce sotto un unico governo numerosi popoli di sistemi stellari diversi, e delle loro avventure nell esplorazione del cosmo', 1, 15.00, 'imm/startrek.jpg'),
(default, 'fantascienza', 'Battlestar Galactica', 'serie completa', 'in una lontana parte della nostra galassia una civiltà umana vive sparsa su un gruppo di pianeti noti come le Dodici Colonie, su cui si è trasferita dopo essere migrata dall ancestrale mondo nativo di Kobol. Le Dodici Colonie sono in conflitto da decenni con la razza cibernetica dei cyloni, il cui obiettivo è lo sterminio della specie umana', 1, 70.00, 'imm/battgala.jpg'),
(default, 'fantascienza', 'Doctor Who', '1', 'Ha per protagonista un Signore del Tempo, cioè un alieno viaggiatore del tempo, che si fa chiamare semplicemente Il Dottore. Il Dottore esplora l universo a bordo del TARDIS, una macchina senziente capace di viaggiare nello spazio e nel tempo attraverso il cosiddetto vortice temporale.', 1, 15.00, 'imm/docwho.jpg'),
(default, 'horror', 'The Walking Dead', 'due', 'A seguito di un epidemia che ha decimato la popolazione mondiale generando un esercito di zombie, chiamati “walkers“, vari gruppi di sopravvissuti cercano di andare avanti con le loro vite cercando posti sicuri e spesso combattendo tra di loro per rubare le risorse altrui.', 1, 15.00, 'imm/thewalkingdead.jpg'),
(default, 'horror', 'Buffy L Ammazza Vampiri', 'serie completa', 'La serie segue le vicende di Buffy Summers, una studentessa di liceo che scopre di essere dotata di poteri straordinari e per questo è destinata a proteggere la terra da vampiri e altri mostri che minacciano il nostro pianeta.', 1, 80.00, 'imm/buffy.jpg'),
(default, 'horror', 'American Horror Story', '1-3', 'Suddivisa in stagioni completamente indipendenti tra di loro ognuna con un titolo differente dalle altre', 1, 65, 'imm/americanhorror.jpg'),
(default, 'medical drama', 'ER-Medici in prima linea', '1', 'La serie è ambientata nel pronto soccorso (ER infatti è l acronimo di Emergency Room, in italiano "pronto soccorso") del policlinico universitario di Chicago, il County General Hospital.', 1, 15.00, 'imm/er.jpg'),
(default, 'medical drama', 'Dr House Medical Division', 'serie completa', 'a serie ruota intorno alla vita del Dottor Gregory House un medico luminare di lunga e provata esperienza tuttavia caratterizzato da tratti di personalità molto particolari e fuori dal comune', 1, 85.00, 'imm/drhouse.jpg'),
(default, 'medical drama', 'Grey s Anatomy', '1-11', 'La serie racconta la vita sentimentale e lavorativa di Meredith Grey (da cui prende il nome la serie, ma in realtà si rifà anche al celebre manuale di anatomia intitolato “Anatomia del Gray“), medico tirocinante del Seattle Grace Hospital e di alcuni colleghi e amici.', 1, 110.00, 'imm/greys.jpg'),
(default, 'teen drama', 'Beverly Hills 90210', '1', 'La serie segue le vicissitudini di un gruppo di adolescenti dell alta borghesia, abitanti nel quartiere VIP di Beverly Hills, a Los Angeles.', 1, 20.00, 'imm/beverlyhills.jpg'),
(default, 'teen drama', 'Una mamma per amica', 'serie completa', 'La serie esplora le relazioni interpersonali e intergenerazionali in maniera profonda, il tutto compresso in una piccola città con numerosi personaggi particolari', 1, 120.00, 'imm/unamammaperamica.jpg'),
(default, 'teen drama', 'One Tree Hill', 'serie completa', 'Lo show è ambientato nella fittizia città di Tree Hill in Carolina del Nord e originalmente seguiva le vite di due fratellastri, Lucas Scott e Nathan Scott. Il loro rapporto evolve da acerrimi nemici a fratelli devoti, e questo, insieme al basket e le relazioni tira e molla dei due ragazzi con i personaggi femminili, sono gli elementi portanti della serie.', 1, 120.00, 'imm/onetreehill.jpg');


INSERT INTO cofanetti_venditori(idCofanetto, idVenditore, numero)
VALUES (1,6,1),
(2,6,1),
(3,9,1),
(4,10,1),
(5,8,1),
(6,7,1),
(7,7,1),
(8,6,1),
(9,10,1),
(10,8,1),
(11,8,1),
(12,6,1),
(13,7,1),
(14,10,1),
(15,9,1),
(16,9,1),
(17,9,1),
(18,9,1),
(19,6,1),
(20,8,1);



INSERT INTO cofanetti_acquistati(idCofanetto, idCliente)
VALUES 
(40, 21),
(39, 23),
(38, 25),
(37, 24);



